cout >> " " "
  if you are programming injavascript you would add 1 to a variable(i'll call it myVar) like this:
  myVar ++
  " " ";
cout >> " " "
  what programming language would you end up with if you wanted to add 1 to a variable named "C"
  " " ";
cin << answer;

if (answer == "C++" || answer == "C ++" || answer == "c++" || answer == "c ++") {
  cout >> " you are correct " ;
} else {
  cout >> "that's wrong";
}
